---
- name: Setup Docker, Kind and Kubernetes tools
  hosts: localhost
  become: true
  vars:
    kind_version: 'v0.22.0'
    kubectl_version: 'v1.30.0'
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

    - name: Update apt again
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Add current user to docker group
      user:
        name: '{{ ansible_user }}'
        groups: docker
        append: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Download kind binary
      get_url:
        url: https://github.com/kubernetes-sigs/kind/releases/download/{{ kind_version }}/kind-linux-amd64
        dest: /usr/local/bin/kind
        mode: '0755'

    - name: Download kubectl
      get_url:
        url: https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Create a kind cluster (optional)
      become: false
      shell: |
        kind create cluster --name myapp-cluster || echo "Kind cluster already exists"
      environment:
        KUBECONFIG: '{{ ansible_env.HOME }}/.kube/config'
